---
title: "p8105_hw5_sz2800"
author: "Stephanie Zhen"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  janitor::clean_names() %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(species = as.character(species))
```

```{r}
iris_missing_na = function(x) {
  if (is.numeric(x)) {
    x = replace_na(x, mean(x, na.rm = TRUE))}
  else if (!is.numeric(x)){
    x = replace_na(x, "virginica")
  }
}

output_iris = map_df(iris_with_missing, iris_missing_na)

```

```{r}
all_files = list.files(path = "./data") %>% 
  tibble::enframe(name = NULL) %>% 
  mutate(
    read_all_data = map(value, ~read_csv(str_c("./data/", .x)))
    ) %>% 
  unnest(read_all_data) %>% 
  separate(value, into = c("txt_group", "subject_id")) %>% 
  mutate(subject_id = str_c(txt_group, subject_id))
  
  files_tidy = pivot_longer(
    all_files,
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "sub_obs") %>%
    mutate(week = as.numeric(week))
  
files_tidy_plot = ggplot(files_tidy, aes(x = week, y = sub_obs, color = txt_group, group = subject_id)) +
  geom_path() 

files_tidy_plot
```


```{r}
prob3_sim_reg = function(n = 30, beta0 = 2, var = 50, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, var)
  )
  
  ls_sim = lm(y ~ x, data = sim_data) %>% 
    broom::tidy() %>% 
    filter(term == "x")
      
  tibble(
    beta1_hat = pull(ls_sim, estimate),
    p_value = pull(ls_sim, p.value)
  )
}
```


```{r}
output_sim_reg = 
  tibble(beta1 = c(1, 2, 3, 4, 5, 6)) %>% 
  mutate(
    output_lists = map(.x = beta1, ~rerun(10000, prob3_sim_reg(beta1 = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)

output_sim_reg

```

```{r}
ls_reject_pre = output_sim_reg %>%
  group_by(beta1) %>% 
  summarize(n = n(), 
            reject = sum(p_value <= 0.05), 
            non_reject = sum(p_value > 0.05), 
            prop_reject = (reject/n))

ls_reject_hist = ls_reject_pre %>% 
  ggplot(aes(x = beta1, y = prop_reject)) +
  geom_histogram(stat = "identity")

ls_reject_hist
```

```{r}
ls_beta_avg_pre = output_sim_reg %>%
  group_by(beta1) %>% 
  mutate(avg_beta_hat = mean(beta1_hat))

ls_beta_avg_pre

ls_bavg_rej_pre = output_sim_reg %>% 
  group_by(beta1) %>% 
  filter(p_value <= 0.05) %>% 
  mutate(avg_betah_rej = mean(beta1_hat))

ls_bavg_rej_pre
```


